### ISSUE TITLE
Error de encoding en menú de aplicaciones

### ISSUE THREAD

**Issue by sergiovier** [SIU-Toba/js-app-launcher#3]
No se muestra bien la opción "más" que permite ver elementos adicionales en el menú de aplicaciones. 

Podría cambiarse a "Expandir" para evitar estas situaciones.

**Comment by enfoqueNativo** [comment]
Agree.. lo cambio y subo como 1.0.4

**Comment by sergiovier** [comment]
https://github.com/SIU-Toba/js-app-launcher/commit/3db3edab759c89d81aaf74f635e796340384faf8
